image: maven:3-jdk-11

stages:
- build
- customize

variables:
  MAVEN_OPTS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Dmaven.repo.local=.m2/repository"
  GIT_STRATEGY: fetch
  GIT_DEPTH: 50

.ear-upload: &ear-upload
  after_script:
  - mv src/ear/target/eaas-server.ear .
  artifacts:
    paths:
    - eaas-server.ear

.maven-cache: &maven-cache
  needs:
  - job: standalone-server-build
    artifacts: false
  cache:
    key: maven-repo
    policy: pull
    paths:
    - .m2/repository

# build standalone configuration and update maven's cache
standalone-server-build:
  stage: build
  script:
  - mvn -f src/pom.xml clean package -Dskip-docs=false -T1C
  - ./ci/scripts/upload-api-docs.sh
        "emil:${PWD}/src/emil/target/apidocs"
        "environment-proposer:${PWD}/src/environment-proposer/target/apidocs"
        "dig-pub-sharing:${PWD}/src/dig-pub-sharing/target/apidocs"
  <<: *ear-upload
  cache:
    key: maven-repo
    policy: pull-push
    paths:
    - .m2/repository

# build gateway configuration
gateway-build:
  stage: customize
  script:
    - cp -f src/ear/src/main/application/META-INF/{deployment-gateway.xml,jboss-deployment-structure.xml}
    - mvn -f src/pom.xml clean package -P '!emucomp' -pl ear -am -T1C
  <<: *ear-upload
  <<: *maven-cache

# build emucomp configuration
emucomp-build:
  stage: customize
  script:
    - cp -f src/ear/src/main/application/META-INF/{deployment-emucomp.xml,jboss-deployment-structure.xml}
    - mvn -f src/pom.xml clean package -P emucomp,imagearchive,blobstore -pl ear -am -T1C
  <<: *ear-upload
  <<: *maven-cache
